apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codebot
  template:
    metadata:
      labels:
        app: codebot
    spec:
      containers:
      - name: codebot-container
        image: munevvernure/codebotapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: codebot-service
spec:
  type: NodePort
  selector:
    app: codebot
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
